CLIENTS: Add PATCH methods
hassanhabib/RESTFulSense pull request #135
Opened 2023-05-16 22:22 UTC by diogod3

Closes #134

2023-05-17 08:07 UTC, cjdutoit commented
LGTM

2023-05-17 08:11 UTC, cjdutoit commented on RESTFulSense/Clients/IRESTFulApiClient.cs
> +            bool ignoreDefaultValues = false);
Missing the following that was added to the IRESTFulApiFactoryClient

```
        ValueTask<T> PatchContentAsync<T>(
            string relativeUrl,
            T content,
            CancellationToken cancellationToken,
            string mediaType = "text/json",
            bool ignoreDefaultValues = false);
```

2023-05-17 08:12 UTC, cjdutoit commented on RESTFulSense/Clients/RESTFulApiClient.cs
> +
Missing
```
        public async ValueTask<T> PatchContentAsync<T>(
            string relativeUrl,
            T content,
            CancellationToken cancellationToken,
            string mediaType = "text/json",
            bool ignoreDefaultValues = false)
        {
            HttpContent contentString = ConvertToHttpContent(content, mediaType, ignoreDefaultValues);

            HttpResponseMessage responseMessage =
               await this.httpClient.PatchAsync(relativeUrl, contentString, cancellationToken);

            await ValidationService.ValidateHttpResponseAsync(responseMessage);

            return await DeserializeResponseContent<T>(responseMessage);
        }
```

2023-05-17 08:13 UTC, cjdutoit requested changes
IRESTFulApiFactoryClient and IRESTFulApiClient not in sync

2023-05-17 08:27 UTC, diogod3 commented
Thanks @cjdutoit

I used the PUT methods as a guideline and that method was missing from the interface, but it was present in the implementation 😅 I added it for both PUT and PATCH.

2023-08-22 13:21 UTC, SlimAhmad commented
@cjdutoit  would this be merged anytime soon, i'll like to make use of the patch method in my library

2024-03-26 08:31 UTC, closed without merging